=== WhitePoplar022/hella/hella-common/src/main/resources/job_executor_jobplan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<xs:import namespace="http://www.w3.org/2001/XMLSchema-instance"
		schemaLocation="xsi.xsd" />
		
	<xs:element name="jobPlans">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="jobPlan" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="jobPlan" >
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="1" ref="start" />
				<xs:choice maxOccurs="unbounded">
					<xs:element minOccurs="0" maxOccurs="unbounded" ref="action" />
					<xs:element minOccurs="0" maxOccurs="1" ref="fork" />
					<xs:element minOccurs="0" maxOccurs="1" ref="join" />
				</xs:choice>
				<xs:element minOccurs="1" maxOccurs="1" ref="fail" />
				<xs:element minOccurs="1" maxOccurs="1" ref="end" />
			</xs:sequence>
			<xs:attribute name="cronExpression" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="30" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			
			<xs:attribute name="id" use="required" type="xs:integer" />
			<xs:attribute name="ignoreError" use="optional" type="xs:boolean" />
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="40" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute> 
			<xs:attribute name="cronType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="simple" />
						<xs:enumeration value="cron" />
						<xs:enumeration value="event" />
					</xs:restriction>
				</xs:simpleType> 
			</xs:attribute>
			<xs:attribute name="type" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="local" />
						<xs:enumeration value="distributed" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="event" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="start">
		<xs:complexType>
			<xs:attribute name="to" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="40" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="executorClusterID" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="20" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="action">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="job">
					<xs:sequence>
						<xs:element ref="ok" />
						<xs:element ref="error" />
					</xs:sequence>
					<xs:attribute name="delayTime" use="optional" type="xs:integer" />
					<xs:attribute name="delayType" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="soft" />
								<xs:enumeration value="hard" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="errorMaxRedoTimes" use="optional"
						type="xs:integer" />
					<xs:attribute name="name" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="0" />
								<xs:maxLength value="40" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="errorRedoPeriod" use="optional" type="xs:integer" />
					<xs:attribute name="executorClusterID" use="optional">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="0" />
							<xs:maxLength value="20" />
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ok">
		<xs:complexType>
			<xs:attribute name="to" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="40" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="error">
		<xs:complexType>
			<xs:attribute name="to" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="40" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="fork">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="2" maxOccurs="unbounded" ref="path" />
			</xs:sequence>
			<xs:attribute name="joinName" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="40" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="40" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>

		</xs:complexType>
	</xs:element>
	<xs:element name="path">
		<xs:complexType>
			<xs:attribute name="to" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="40" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="join">
		<xs:complexType>
			<xs:attribute name="forkName" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="40" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="40" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="to" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="40" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="fail">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" ref="job" />
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="40" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="executorClusterID" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="20" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="end">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" ref="job" />
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="40" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="executorClusterID" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="20" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="job">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" ref="job" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="job">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="executionContent" />
				<xs:element ref="jobClassName" />
				<xs:element ref="args" />
				<xs:element ref="description" />
			</xs:sequence>
			<xs:attribute name="mode" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="httpGet" />
						<xs:enumeration value="httpPost" />
						<xs:enumeration value="script" />
					</xs:restriction>
				</xs:simpleType> 
			</xs:attribute>
			<xs:attribute name="executeUser" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0" />
						<xs:maxLength value="20" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="executionContent">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1" />
				<xs:maxLength value="80" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="jobClassName">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1" />
				<xs:maxLength value="80" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="args">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="0" />
				<xs:maxLength value="80" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="description">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="0" />
				<xs:maxLength value="80" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== WhitePoplar022/hella/hella-engine/webapp/upload/ZY_Executor_Test/20140107155435_job_executor_dist_jobplan.xml
<?xml version="1.0" encoding="UTF-8"?>
<jobPlans  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="job_executor_jobplan.xsd">
	
 <jobPlan id="1" name="test1" type="distributed" ignoreError="true" cronType="simple" cronExpression="120">
		<start to="fork1" />
		<fork name="fork1" joinName="join1">
			<path to="executor_action1" />
			<path to="executor2_action1" />
		</fork>
		<action name="executor_action1" delayTime="1" delayType="soft" executorClusterID="ZY_Executor_Test">
			<job mode="script" executeUser="zhangxianquan">
				<executionContent>test/shell/xJobA1.sh</executionContent>
				<jobClassName>com.zhangyue.hella.common.model.ShellXjob</jobClassName>
				<args>XJob_A1</args>
				<description>This is first job on executor : ZY_Executor_Test.</description>
			</job>
			<ok to="executor_action2" />
			<error to="fail" />
		</action>
		<action name="executor_action2" delayTime="1" delayType="soft" executorClusterID="ZY_Executor_Test">
			<job mode="script" executeUser="zhangxianquan">
				<executionContent>test/shell/xJobA2.sh</executionContent>
				<jobClassName>com.zhangyue.hella.common.model.ShellXjob</jobClassName>
				<args>XJob_A2</args>
				<description>This is second job on executor : ZY_Executor_Test.</description>
			</job>
			<ok to="join1" />
			<error to="fail" />
		</action>
		<action name="executor2_action1" delayTime="1" delayType="soft" executorClusterID="ZY_Executor2_Test">
			<job mode="script" executeUser="zhangxianquan">
				<executionContent>test/shell/xJobB1.sh</executionContent>
				<jobClassName>com.zhangyue.hella.common.model.ShellXjob</jobClassName>
				<args>XJob_B1</args>
				<description>This is first job on executor : ZY_Executor2_Test.</description>
			</job>
			<ok to="executor2_action2" />
			<error to="fail" />
		</action>
		<action name="executor2_action2" delayTime="1" delayType="soft" executorClusterID="ZY_Executor2_Test">
			<job mode="script" executeUser="zhangxianquan">
				<executionContent>test/shell/xJobB2.sh</executionContent>
				<jobClassName>com.zhangyue.hella.common.model.ShellXjob</jobClassName>
				<args>XJob_B2</args>
				<description>This is second job on executor : ZY_Executor2_Test.</description>
			</job>
			<ok to="join1" />
			<error to="fail" />
		</action>
		<join name="join1" forkName="fork1" to="merge_action" />
		<action name="merge_action" delayTime="1" delayType="soft" executorClusterID="ZY_Executor_Test">
			<job mode="script" executeUser="zhangxianquan">
				<executionContent>test/shell/xJobC.sh</executionContent>
				<jobClassName>com.zhangyue.hella.common.model.ShellXjob</jobClassName>
				<args>XJob_C</args>
				<description>This is last job on executor : ZY_Executor_Test and merge above job output.</description>
			</job>
			<ok to="end" />
			<error to="fail" />
		</action>
		<fail name="fail" />
		<end name="end" />
	</jobPlan>
	
</jobPlans>

=== WhitePoplar022/hella/hella-engine/webapp/upload/ZY_Executor_Test/20140127154902_job_executor_multijob_jobplan.xml
<?xml version="1.0" encoding="UTF-8"?>
<jobPlans  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="job_executor_jobplan.xsd">
	
 <jobPlan id="2" name="multi_job_JP" type="local" ignoreError="true" cronType="simple" cronExpression="120">
		<start to="fork1" />
		<fork name="fork1" joinName="join1">
			<path to="action11" />
			<path to="action21" />
		</fork>
		<action name="action11" delayTime="1" delayType="soft">
			<job mode="script" executeUser="zhangxianquan">
				<executionContent>test/shell/xJobA1.sh</executionContent>
				<jobClassName>com.zhangyue.hella.common.job.impl.ShellXjob</jobClassName>
				<args>XJob_A1</args>
				<description>This is first job on executor : ZY_Executor_Test.</description>
			</job>
			<ok to="action12" />
			<error to="fail" />
		</action>
		<action name="action12" delayTime="1" delayType="soft">
			<job mode="script" executeUser="zhangxianquan">
				<executionContent>test/shell/xJobA2.sh</executionContent>
				<jobClassName>com.zhangyue.hella.common.job.impl.ShellXjob</jobClassName>
				<args>XJob_A2</args>
				<description>This is second job on executor : ZY_Executor_Test.</description>
			</job>
			<ok to="join1" />
			<error to="fail" />
		</action>
		<action name="action21" delayTime="1" delayType="soft">
			<job mode="script" executeUser="zhangxianquan">
				<executionContent>test/shell/xJobB1.sh</executionContent>
				<jobClassName>com.zhangyue.hella.common.job.impl.ShellXjob</jobClassName>
				<args>XJob_B1</args>
				<description>This is first job on executor : ZY_Executor_Test.</description>
			</job>
			<ok to="action22" />
			<error to="fail" />
		</action>
		<action name="action22" delayTime="1" delayType="soft">
			<job mode="script" executeUser="zhangxianquan">
				<executionContent>test/shell/xJobB2.sh</executionContent>
				<jobClassName>com.zhangyue.hella.common.job.impl.ShellXjob</jobClassName>
				<args>XJob_B2</args>
				<description>This is second job on executor : ZY_Executor_Test.</description>
			</job>
			<ok to="join1" />
			<error to="fail" />
		</action>
		<join name="join1" forkName="fork1" to="merge_action" />
		<action name="merge_action" delayTime="1" delayType="soft">
			<job mode="script" executeUser="zhangxianquan">
				<executionContent>test/shell/xJobC.sh</executionContent>
				<jobClassName>com.zhangyue.hella.common.job.impl.ShellXjob</jobClassName>
				<args>XJob_C</args>
				<description>This is last job on executor : ZY_Executor_Test and merge above job output.</description>
			</job>
			<ok to="end" />
			<error to="fail" />
		</action>
		<fail name="fail" />
		<end name="end" />
	</jobPlan>
	
</jobPlans>

=== WhitePoplar022/hella/hella-executor/src/test/resources/job_executor_jobplan.xml
<?xml version="1.0" encoding="UTF-8"?>
<jobPlans  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="job_executor_jobplan.xsd">
	
 <jobPlan id="1" name="test1" type="local" ignoreError="true" cronType="simple" cronExpression="120">
		<start to="test" />
		<action name="test" delayTime="1" delayType="soft">
			<job mode="script" executeUser="zhangxianquan">
				<executionContent>test/shell/xJobA1.sh</executionContent>
				<jobClassName>com.zhangyue.hella.common.job.impl.ShellXjob</jobClassName>
				<args>access</args>
				<description>syncLogDataD1 sync data to the bjcer.</description>
			</job>
			<ok to="end" />
			<error to="fail" />
		</action>
		<fail name="fail" />
		<end name="end" />
	</jobPlan>
	
</jobPlans>
